source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/zzttwzq/WSpecRepo.git'

use_frameworks!

target 'WExpandLibrary_Example' do
  pod 'WExpandLibrary', :path => '../'
  pod ‘WBasicLibrary’
end
